platform :ios, '8.0'

target 'CHOCascadeViewController_Example' do
  pod 'CHOCascadeViewController', :path => '../'

  target 'CHOCascadeViewController_Tests' do
    inherit! :search_paths
    
  end
end
